### ISSUE TITLE
在管理面板更改配色之后貌似用户中心的按钮的颜色不会改变？

### ISSUE THREAD

**Issue by tnqzh123** [printempw/blessing-skin-server#99]
如图，Blessing Skin Server v3.3.1，我记得群里讨论过这个问题的，但是忘了有没有解决方案了...
强迫症感觉很难受
![fireshot pro screen capture 003 - - littleskin - mcskin_littleservice_cn_user](https://user-images.githubusercontent.com/16630630/31848226-d5086806-b65f-11e7-8da4-6ed828566069.png)

**Comment by ghost** [comment]
哈哈

**Comment by ghost** [comment]
熟悉的头像23333

**Comment by g-plane** [comment]
你是指「签到」和其它类似按钮的颜色吗？那个 AdminLTE 设好的，而且我不建议改（因为具有标识作用，见下表）。确实觉得不爽，改样式就行。

## 附录

### 颜色与对应的标识

|代码中的标识|对应的颜色|
|:-----------:|:---------:|
|`default`|白色|
|`primary`|蓝色|
|`success`|绿色|
|`warning`|黄色|
|`danger`|红色|

虽然能通过 CSS 强制修改颜色，不过这样按钮也就会失去「此操作的重要程度」的含义。

### 修改方法

进入「管理面板」-->「个性化」，在「自定义 CSS」处添加如下代码：
```css
.btn-primary {    /* 除了 primary，还有其它种类的按钮，参见上表 */
    background-color: #000000;    /* 在这里修改颜色 */
}
```
